src/contracts/proxies/HaiSafeManager.sol
src/interfaces/proxies/ISafeManager.sol
src/interfaces/proxies/IVault721.sol

update safe manager open/xfer safe

---

src/script/test/DeployOrFindProxy.s.sol
src/script/test/DeployProxy.s.sol
src/script/test/GenerateDebt.s.sol
src/script/test/LockCollateral.s.sol
src/script/test/OpenSafe.s.sol
src/script/test/utils/TestContracts.s.sol
src/script/test/utils/TestHelper1.s.sol
src/script/test/utils/TestHelper2.s.sol

PR to replace OP-Buggin 
These scripts depend on the contract being pulled from HAI, as recent changes have been made to the methods in Proxy Actions

add live tests in scripts

---

src/contracts/proxies/Vault721.sol

changes Proxy owner from Vault721 contract to the user's wallet

change proxy build from address.this to user addr

---

src/script/Common.s.sol
src/script/Contracts.s.sol
src/script/GoerliContracts.s.sol
src/script/GoerliDeployment.s.sol
src/test/scopes/ProxyUser.t.sol

Update deployment params and contracts for NFT-mod contracts

Deployment

---

src/script/GoerliParams.s.sol

change surplus auction params to recycle gov tokens back to govenor

surplus param

---

src/contracts/proxies/ODSafeManager.sol

Will need to make another PR updating imports once all other PRs are in.

renamed HaiSafeManager to ODSafeManager

---

src/contracts/oracles/UniV3Relayer.sol
src/script/GoerliContracts.s.sol
src/script/postdeployment/DeployLiqPool.s.sol
src/script/postdeployment/DeployUniV3Relayer.s.sol
src/script/postdeployment/GetLiqPool.s.sol
src/script/test/GenerateDebt.s.sol
src/script/test/LockCollatAndGenDebt.s.sol
src/script/test/LockCollateral.s.sol
src/script/test/utils/Deployment.s.sol

add getPool script

---

src/contracts/proxies/Vault721.sol

only inherit ERC721Enumerable to avoid multi-overrides

Enumerable is ERC721, refine inheritance

---

src/script/Deploy.s.sol

Closes #30 
uses forge ffi cheatcode to call git function, and output result.

add git commit output into deployer

---

src/contracts/proxies/NFTRenderer.sol
src/contracts/proxies/ODSafeManager.sol
src/contracts/proxies/Vault721.sol
src/interfaces/proxies/IVault721.sol

fix initialization, add completed IVault721 interface

---

package.json
script/Common.s.sol
script/Deploy.s.sol
script/GoerliParams.s.sol
script/govdeployment/DeployGovernor.s.sol
src/contracts/gov/ODGovernor.sol
test/nft/GoerliForkSetup.t.sol
test/nft/governor/GovActions.t.sol

Test complete
Need to wait for next deployment to run test against DAO authorized protocol
closes #85

Governor action

---

.gitmodules
src/contracts/proxies/NFTRenderer.sol

fix percent spacing

---

src/contracts/proxies/ODProxy.sol
src/contracts/proxies/Vault721.sol

added version comment

---

src/contracts/proxies/NFTRenderer.sol

change desc to list of attributes

---

package.json
script/Common.s.sol
script/Deploy.s.sol
script/GoerliDeployment.s.sol
script/Registry.s.sol
script/nft/RedeployRenderer.s.sol
test/e2e/Deploy.t.sol

separate goerli/mainnet governor deployments and odg airdrops

---

src/contracts/proxies/Vault721.sol

Add requireMinted check

---

script/Common.s.sol
test/e2e/Deploy.t.sol

run `forge test -w --match-test test_Grant_Auth --ffi --match-contract E2EDeploymentGoerliTest -vvvv` to see passing test
closes #197

197 fix deployment authorization test

---

foundry.toml

change solc versioning

---

src/contracts/proxies/ODSafeManager.sol
src/interfaces/proxies/IODSafeManager.sol

237 sync od safe manager fixes with hai

---

script/Common.s.sol
script/Registry.s.sol
script/gov/DeployGovernor.s.sol
src/contracts/gov/ODGovernor.sol

change gov settings to dynamic params

---

src/contracts/proxies/ODSafeManager.sol
src/interfaces/proxies/IODSafeManager.sol

Closed #236
Added some simple functionality to distinguish between allowed actions for the SafeOwner vs. approved addresses.

Closed #236 / #171 only safe owner can authorize additional approvals

---

test/testnet/e2e/Oracles.t.sol

fix e2e oracle tests

---

src/contracts/proxies/actions/BasicActions.sol
src/interfaces/proxies/actions/IBasicActions.sol
test/testlocal/nft/anvil/AnvilFork.t.sol
test/testlocal/nft/anvil/NFT.t.sol

This does not close an issue, but fixes a compilation error brought in by recent PR.

compilation pass

---

src/contracts/proxies/actions/BasicActions.sol

not sure how this one slipped through

fix simple broken build

---

foundry.toml
src/contracts/proxies/actions/BasicActions.sol
test/testnet/simulations/SimulationPIDController.t.sol

run `yarn test:simulations` to see the passing tests
closes #285

fix simulation tests

---

README.md
script/gov/UpdatePidControllerAction/ProposeUpdatePidController.s.sol

add docs for pid controller action

---

script/postdeployment/base/CTypeBase.s.sol
src/contracts/proxies/NFTRenderer.sol
src/contracts/proxies/ODSafeManager.sol
src/contracts/proxies/Vault721.sol
src/contracts/settlement/GlobalSettlement.sol
src/interfaces/proxies/IVault721.sol
test/testlocal/nft/anvil/AnvilFork.t.sol

closes #277 
See [here](https://github.com/open-dollar/od-contracts/issues/277#issuecomment-1867932504) for the implementation details

NFV Frontrunning Issue Fix

---

test/testnet/single/SurplusAuctionHouse.t.sol

Closes #305
Protocol Token required initialization in order to pass authorization check.  Ez mid

fixed single surplus auction tests by initializing the protocol token

---

test/testlocal/nft/anvil/governor/Proposal.t.sol
test/testnet/single/SAFEEngine.t.sol

This PR fix the test `test_liquidate_when_system_surplus`.
The test was missing the address configuration `extraSurplusReceiver`.

fix test_liquidate_when_system_surplus

---

src/contracts/proxies/Vault721.sol
test/testlocal/nft/anvil/NFT.t.sol

Tests for new NFV Frontrunning features

---

script/Deploy.s.sol
test/testnet/e2e/Deploy.t.sol

rm airdrop from sepolia and mainnet

---

test/testlocal/nft/anvil/deployment/AnvilContracts.t.sol
test/testlocal/nft/anvil/deployment/AnvilDeployment.t.sol

fix a compile error that resulted from merge conflict

fix compile conflict

---

test/testnet/unit/proxies/ODProxy.t.sol

close ODProxy #378
This PR add tests to ODProxy contract.

add tests to ODProxy

---

test/testnet/e2e/E2ENFT.t.sol

Fix E2E NFT Tests

---

script/states/DebtAuction.s.sol
script/states/DebtState.s.sol
script/states/LiquidationAuction.s.sol
script/testScripts/postJoin/GetCTypes.s.sol
script/testScripts/postJoin/JoinCType.s.sol
src/contracts/proxies/actions/BasicActions.sol
src/contracts/utils/Disableable.sol
src/contracts/utils/Modifiable.sol
test/testlocal/nft/anvil/AnvilFork.t.sol
test/testlocal/nft/anvil/NFT.t.sol
test/testnet/scopes/DirectUser.t.sol
test/testnet/scopes/ProxyUser.t.sol

Fix Warnings

---

test/testnet/e2e/Deploy.t.sol
test/testnet/single/AccountingEngine.t.sol

closes #404 
merged stargardens branch and added a test to complete coverage of the accounting engine.

Deadce11 accounting engine test

---

test/testnet/e2e/Deploy.t.sol
test/testnet/unit/proxies/NFTRenderer.t.sol
test/testnet/unit/proxies/Vault721.t.sol

closes #419 
changed tests to only check that a string is returned.  also  fixed the symbol string in the fuzzed data because the random strings were causing issues.

NftRenderer test fix

---

src/contracts/oracles/DenominatedOracle.sol

* fix: denominatedOracle divide by 0
* refactor: remove duplicate error

Fix: avoid `DenominatedOracle` divide by 0

---

src/contracts/oracles/DelayedOracle.sol
test/testnet/e2e/Oracles.t.sol

* fix: delayed oracle store invalid feed
* refactor: simplify updateResult
* fix: updated lastUpdateTime after invalid feed refetching
---------

Fix: `DelayedOracle` store invalid feed

---

src/contracts/utils/CollateralJoin.sol

* fix: cei pattern in CollateralJoin
* fix: safeTransferFrom() as a check

Fix: exit CEI pattern in CollateralJoin

---

src/contracts/tokens/TokenDistributor.sol
src/interfaces/tokens/ITokenDistributor.sol
test/testnet/unit/TokenDistributor.t.sol

* refactor: reuse _canClaim(..)
* docs: added natspec
* refactor: external/internal method instead of public

Fix: reuse `_canClaim(..)` in TokenDistributor

---

src/contracts/AccountingEngine.sol

* fix: auctiondebt check after settle
* test: re-enable test and fix check
---------

Fix: auctiondebt check after settle

---

script/testScripts/gov/ArbitraryAction/TestProposal.s.sol

closes #450
note: needs to be proposed by account holding protocolToken since it is called via ODGovernor, not the TimelockController

add empty action

---

script/Common.s.sol
script/Deploy.s.sol
test/testnet/e2e/Deploy.t.sol

close #488

---

README.md
script/testScripts/gov/ERC20TransferAction/ProposeERC20Transfer.s.sol

add erc20 transfer proposal

---

script/MainnetParams.s.sol

This PR closes https://github.com/open-dollar/od-contracts/issues/524

debt ceiling to 10M

---

src/contracts/SAFEEngine.sol
src/contracts/proxies/ODSafeManager.sol
src/interfaces/ISAFEEngine.sol
test/testnet/single/AccountingEngine.t.sol
test/testnet/unit/SAFEEngine.t.sol

closes #531 
In SAFEEngine:
modifySafeCollateralization now checks the safeManager that the safe being modified is a valid safeHandler.
added initializeSafeManager function to SAFEEngine that is called  in the ODSafeManger constructor.
working on fixing the SAFEEngine tests and adding new tests for the added functionality

OD-4 Debt w.o. vault

---

test/testnet/e2e/Deploy.t.sol
test/testnet/unit/proxies/Vault721.t.sol

add missing transferFrom safeTransferFrom tests

---

tasks/prepareForSdk.js

prepareForSdk cleanup

---

script/testScripts/gov/QueueProposal.s.sol
src/contracts/gov/ODGovernor.sol
test/unit/ODGovernor.t.sol

closes #621
Swapped governor bravo to GovernorCountingSimple and adjusted governance tests and scripts.

ODGovernor contract size fix.

---

codecov.yml

closes #618
This PR (#618) introduces targets to code coverage

add target to codecov

---

script/MainnetParams.s.sol
test/unit/LiquidationEngine.t.sol

This PR adds a Fat Saviour that will burn all available gas, is part of review of #619 issue

add saviour gas burner

---

script/Common.s.sol
script/Contracts.s.sol
script/Deploy.s.sol
script/MainnetDeployment.s.sol
script/MainnetParams.s.sol
script/Registry.s.sol
script/SepoliaDeployment.s.sol
script/SepoliaParams.s.sol
script/SepoliaScript.s.sol
script/anvil/deployment/AnvilDeployment.t.sol
test/e2e/Deploy.t.sol

"governor" is now "tlcGov", so as not to be confused with the MainDeployment's instance of `timelockController`
closes #664

Update Deployment Variable Naming

---

test/unit/proxies/NFTRenderer.t.sol

Fix NFVRenderer Tests

---

package.json

Increase Fuzz Rejection Rate

---

test/unit/ODGovernor.t.sol

closes #683 
Tests work with Open Zeppelin version 4.9.6

Pass Governance Unit Tests
