.husky/pre-commit
src/contracts/proxies/Vault721.sol

add a total supply variable to the NFT contract that can be called by the app via `totalSupply()`
This does not account for deleted safes or burned tokens as far as I can tell for now. solves #47

nuke pre commit. add total supply

---

src/contracts/proxies/ODProxy.sol
src/contracts/proxies/Vault721.sol

`setOwner` from Ownable is not used anywhere in protocol. There is another `setOwner` function from an Auth contract, which is used in testing.
solves #76 
solves #71 
solves #24 
solves #23

immutable owner

---

tasks/.gitignore
tasks/prepareForSdk.js

This script enables a repeatable method for converting the deployment addresses into the format expected by the SDK, to reduce human error. 
```sol
// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.19;
abstract contract GoerliContracts {
address public chainlinkRelayerFactoryAddr = 0xf67824c9dD65425600639Bb1F18c08368A147c69;
address public uniV3RelayerFactoryAddr = 0xC2d2F3fcA75D05387DB01214D03B6d1EC5F22e44;
address public denominatedOracleFactoryAddr = 0x290Fdb5878Ac39C888aB0ebdF07c6d5929F6bf65;
address public delayedOracleFactoryAddr = 0x76E0D3f31B633dBeDd07ec21Dd2Af389E6A6E6e0;
```
Becomes
```js
export default {
GEB_SURPLUS_AUCTION_HOUSE: '0x97Ba91F8161c67eC0f5600f96Aa6B78eEcA83E2f',
GEB_DEBT_AUCTION_HOUSE: '0x73098945f3e73caf01909C957A6bd65ED910F637',
GEB_ACCOUNTING_ENGINE: …
```

Script to prep addresses for SDK

---

src/contracts/proxies/ODSafeManager.sol
test/nft/anvil/AnvilFork.t.sol
test/nft/anvil/NFT.t.sol
test/nft/anvil/TransferOwnership.t.sol
test/nft/anvil/deployment/AnvilContracts.t.sol

closes #154 
Bug: 
when transferring 1 safe, `_usrSafes` is set to zero, when it should reduce by 1
Test:
User has 5 safes, transfers 1 safe, retains ownership of remaining 4 safes, however, `_usrSafes` is cleared as if the user does not own any safes.
Next step:
Do we wait from @wei3erHase to give us an update since the HAI team is aware of it?

test transferOwnership

---

package.json
remappings.txt
script/Common.s.sol
script/Deploy.s.sol
script/Registry.s.sol
script/create2/Create2Factory.sol
script/create2/DeployContracts.s.sol
script/create2/DeployCreate2Factory.s.sol
src/contracts/SurplusAuctionHouse.sol
src/contracts/proxies/Vault721.sol
src/contracts/proxies/actions/CommonActions.sol
src/contracts/proxies/actions/DebtBidActions.sol
src/contracts/proxies/actions/SurplusBidActions.sol
src/contracts/settlement/PostSettlementSurplusAuctionHouse.sol
src/contracts/tokens/ProtocolToken.sol
src/contracts/tokens/SystemCoin.sol
src/contracts/tokens/TokenDistributor.sol
src/contracts/utils/AuthorizableUpgradeable.sol
src/contracts/utils/Create2Factory.sol
src/interfaces/tokens/IProtocolToken.sol
src/interfaces/tokens/ISystemCoin.sol
src/interfaces/tokens/ITokenDistributor.sol
test/single/DebtAuctionHouse.t.sol
test/single/StabilityFeeTreasury.t.sol
test/single/SurplusAuctionHouse.t.sol
test/unit/TokenDistributor.t.sol
yarn.lock

closes #25 
Changes:
- add create2 factory and deployment script
- replace constructors w/ initializer functions for: Vault721, SystemCoin, and ProtocolToken (including inherited contracts)
- edit deployment script to deploy above contracts from create2 factory
- add vars to Registry.s.sol for factory address and salts

Vanity deploy

---

.env.example
src/contracts/proxies/ODSafeManager.sol
src/interfaces/proxies/IODSafeManager.sol
test/nft/anvil/AnvilFork.t.sol
test/nft/anvil/NFT.t.sol

- transferCollateral to non safeHandler address will revert with `HandlerDoesNotExist()` custom error
- transferCollateral to safeHandler address will work as expected
- `test_depositCollateral_generateDebt` and `test_generateDebt` tests fixed
closes https://github.com/open-dollar/od-contracts/issues/215

ODSafeManager handlerExists added, draft tests added in NFT.t.sol

---

src/contracts/AccountingEngine.sol

closes #240 
- we do a check after `_settleDebt` in `AccountingEngine.auctionDebt` to ensure that a debt auction cannot be created without bad debt

add missing debt check

---

src/contracts/AccountingEngine.sol

Resolves #214 
* Updates the `AccountingEngine.sol` at lines [#L213](https://github.com/open-dollar/od-contracts/blob/6023a38154c87d0974a3d9fce0e47bfba7057f37/src/contracts/AccountingEngine.sol#L213) and [#L215](https://github.com/open-dollar/od-contracts/blob/6023a38154c87d0974a3d9fce0e47bfba7057f37/src/contracts/AccountingEngine.sol#L215) to use `WAD` instead of `ONE_HUNDRED_WAD` according the the submission recommendation to correct the issue of surplus auctions being created with `_amountToSell` 100x larger than it should be.

fix: surplus auction creation

---

src/contracts/proxies/ODSafeManager.sol

Simple fix for targeting a potentially wrong safe for transfer collateral and debt.  Closed #238

Closed #159 wrong collateral transfer target

---

src/contracts/for-test/MintableVoteERC20.sol
src/contracts/proxies/NFTRenderer.sol
src/contracts/proxies/Vault721.sol
src/contracts/proxies/actions/BasicActions.sol
src/contracts/utils/Modifiable.sol
src/interfaces/proxies/actions/IBasicActions.sol
test/testlocal/nft/anvil/AnvilFork.t.sol
test/testlocal/nft/anvil/NFT.t.sol
test/testnet/single/AccountingEngine.t.sol
test/testnet/single/SAFEEngine.t.sol
test/testnet/single/TransferSAFECollateralAndDebt.t.sol

Closes #291 
Silenced about a dozen compiler warnings.
There are more warnings I could silence - but the warnings also feel like reference pointers in unfinished code.  There's also a couple compiler warnings that are in fact bugs; such as the ones in AddCollateral.t.sol as these functions cannot be restricted to view functions.

silenced compiler warnings

---

test/testnet/e2e/Common.t.sol
test/testnet/e2e/E2EStabilityFeeTreasury.t.sol
test/testnet/e2e/TestParams.t.sol

Closes #304 
This one ended up being a bit of a doozy because of a Forge error telling me the test was injecting `LiquidationEngineCollateralParams` ... when that was just a straight up bug.
There was a new collateral constant that was only partially created.  And so there was a mixup between `WSTETH` and `ETH-A` where they were inconsistently indexing the various mappings by cType.  I also went ahead and fixed all the E2E Stability Fee tests while I was at it ... they simply weren't accounting for access control revocation.

fixed all e2e stability fee tests

---

src/contracts/proxies/ODSafeManager.sol
src/interfaces/proxies/IODSafeManager.sol
test/testlocal/nft/anvil/NFT.t.sol
test/testlocal/nft/anvil/governor/Proposal.t.sol

closes #217 
NOTE: I'm not sure why, but this test breaks `yarn deploy:anvil`. 
It removes `NFTRenderer_Address` and `GlobalSettlementActions_Address` from `AnvilContracts.t.sol`.

safeCan nonce fix + test

---

src/contracts/proxies/ODSafeManager.sol
src/interfaces/proxies/IODSafeManager.sol
test/testlocal/nft/anvil/NFT.t.sol
test/testlocal/nft/anvil/governor/Proposal.t.sol

closes #219 
similar to #346 - review #346 first and close to see the actual changeset in this one
Which means it has the same issue mentioned in #346.
We reuse the nonce saved in `_safeData` to invalidate `handlerCan` in addition to `safeCan`.
`handlerExists` can be removed in favor of `safeHandlerToSafeId`, as long as this invariant holds true: safeId is never 0 for any safe handlers, then `handlerExists` if `safeHandlerToSafeId != 0`.

Handlercan nonce fix

---

package.json
script/Registry.s.sol
script/SepoliaContracts.s.sol
script/SepoliaDeployment.s.sol
script/testScripts/gov/DeployGovernor.s.sol
script/testScripts/user/utils/Deployment.s.sol
src/contracts/proxies/ODProxy.sol
src/contracts/proxies/Vault721.sol

Each audit finding is listed below with the relevant pull request to resolve the issue.
High Risk (2) 🚨🚨
- [26](https://github.com/code-423n4/2023-10-opendollar-findings/issues/26) (Sabnock https://github.com/open-dollar/od-contracts/pull/254) - incorrect calculation of surplus auctions creates surplus imbalance
- [24](https://github.com/code-423n4/2023-10-opendollar-findings/issues/24) (https://github.com/open-dollar/od-contracts/pull/253) -  missing debt check allows for debt auctions of non-existent debt
Medium and low Risk:
- [429](https://github.com/code-423n4/2023-10-opendollar-findings/issues/429) - (https://github.com/open-dollar/od-contracts/pull/288#pullrequestreview-1781807220) proxy actions is missing methods from SafeManager
- …

Sepolia deployment 01 16 2024

---

script/SepoliaContracts.s.sol

In order for `prepareForSdk.js` to run properly, I added back the addresses for system coin and protocol token

Add missing addresses to SepoliaContracts.s.sol

---

.gitmodules
foundry.toml
package.json
script/Common.s.sol
script/Deploy.s.sol

Related to #488 
This PR updates the Foundry library and adds new features for testing. 
It introduces:
`isNetworkAnvil()` to check if running on Anvil.
New modifiers: `runIfFork()` to execute functions only on forks and `restoreOriginalCaller()` to save and restore the original caller's address.
`onFork()` to differentiate Anvil instances running as forks without altering the original `isFork()` behaviour.
Also fix Anvil script, deployment and tests

Better test support

---

.gitmodules
foundry.toml
package.json
script/Common.s.sol
script/Deploy.s.sol
src/contracts/proxies/actions/CommonActions.sol
src/contracts/proxies/actions/SurplusBidActions.sol

Possible related #443 
SafeApprove is deprecated and was already removed from the OZ library.
I think this is a bug, please @daopunk can you confirm?
https://github.com/open-dollar/od-contracts/blob/443c6e17a3c1cdc7e4970dfb3f028a095c1646fe/src/contracts/proxies/actions/CommonActions.sol#L107C5-L114C16
Problem: Using wei and wad and approving twice.
For PR to be effective, we need a new deployment to Sepolia.

Safe approve remove

---

test/testnet/e2e/E2ENFT.t.sol

This PR will close issue #495 
@daopunk the problem i the difference between codebase and deployed version on Sepolia.
This is the same problem of https://github.com/open-dollar/od-contracts/pull/499
```solidity
if (allowance == 0) {
// Approves adapter to take the COIN amount
SafeERC20.safeApprove(IERC20(_systemCoin), _coinJoin, _wad);
} else {
// if approval amount is a non-zero number, increase allowance.
SafeERC20.safeIncreaseAllowance(IERC20(_systemCoin), _coinJoin, _wad);
}
```

Fix E2ENFT #495

---

package.json
test/unit/GlobalSettlement.t.sol

fuzz runs: 128 => 64 (-64)
max rejections: 1000000 => 1200000 (+200000)
Fix one test in GlobalSettlement
- replaced some `vm.assume`s with if statements (less test depth, but still enough fuzz runs per test for it to be relevant)

Fix Vm Max Cheatcode Rejections

---

.gitignore
script/mainnet/GenerateDebt.s.sol
script/mainnet/MainnetScripts.s.sol
src/contracts/proxies/actions/BasicActions.sol

closes #665 
changed the _generateDebt and _lockCollateralAndGenerateDebt, to exit _deltaWad instead of _deltaDebt
[Here](https://optimistic.etherscan.io/address/0xd36b1bD5445374Ceb7Fe4148a719584234Da7Bb0#code) is the hai basic actions for reference.

Basic action exit deltaDebt fix

---

src/interfaces/proxies/IODSafeManager.sol

Add `function liquidationEngine() external view returns (address _liquidationEngine);`

Fix SafeManager Interface

---

.github/workflows/export-abis.yml
package.json
src/contracts/for-test/OracleForTestnet.sol
src/contracts/settlement/GlobalSettlement.sol
src/contracts/settlement/PostSettlementSurplusAuctionHouse.sol
src/contracts/utils/CollateralJoin.sol
src/interfaces/proxies/IODSafeManager.sol
tasks/remap.js
test/e2e/Deploy.t.sol
test/scopes/DirectUser.t.sol
test/scopes/ProxyUser.t.sol
test/single/GlobalSettlement.t.sol
test/single/SAFEEngine.t.sol
test/single/SaveSAFE.t.sol
test/unit/CollateralJoin.t.sol
test/unit/ODGovernor.t.sol

- Exporter action can be added back, since it now supports node 18
- Exporter also exports contracts, to be used in other repos eg. https://github.com/open-dollar/od-seaport-zone and https://github.com/open-dollar/arbitrum-vault-saviour

Update export action
